# Generated by Django 2.1.3 on 2020-07-22 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd_updated',
            field=models.DateField(default=datetime.date(2020, 7, 22)),
        ),
    ]
