# Generated by Django 2.1.3 on 2020-07-23 07:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_pwd_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emergency_first_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_last_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pwd_updated',
            field=models.DateField(default=datetime.date(2020, 7, 23)),
        ),
    ]
