# Generated by Django 2.1.3 on 2020-07-23 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20200723_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pwd_updated',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
