# Generated by Django 2.1.3 on 2020-07-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20200723_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_role',
            field=models.IntegerField(choices=[(2, 'Igor Admin'), (1, 'Company Admin'), (0, 'Regular User')], default=0),
        ),
    ]
