# Generated by Django 2.1.3 on 2020-08-13 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_auto_20200813_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='company_uid',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
