# Generated by Django 2.1.3 on 2020-08-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_company_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_uid',
            field=models.UUIDField(blank=True),
        ),
    ]
