# Generated by Django 2.1.3 on 2020-08-13 19:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20200813_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4),
        ),
    ]
