# Generated by Django 2.1.3 on 2020-08-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20200813_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_uid',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
