# Generated by Django 2.1.3 on 2020-08-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20200813_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='color_mode',
            field=models.CharField(blank=True, choices=[(2, 'Igor Admin'), (1, 'Company Admin'), (0, 'Regular User')], default='theme-default', max_length=400, null=True),
        ),
    ]
