# Generated by Django 2.1.3 on 2020-08-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_user_color_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='color_mode',
            field=models.CharField(blank=True, choices=[('theme-default', 'theme-default'), ('theme-yellow-light', 'theme-yellow-light'), ('theme-blue-gray-dark', 'theme-blue-gray-dark')], default='theme-default', max_length=400, null=True),
        ),
    ]
