# Generated by Django 2.1.3 on 2020-09-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20200830_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='relation',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='telephone',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
