import os

MAIN_DOMAIN = os.getenv("MAIN_DOMAIN")

""" RDS setting information """
DATABASE_NAME = os.getenv("DATABASE_NAME")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_PORT = os.getenv("DATABASE_PORT")

COMPANY_DATABASE_NAME = os.getenv("COMPANY_DATABASE_NAME")
COMPANY_DATABASE_USER = os.getenv("COMPANY_DATABASE_USER")
COMPANY_DATABASE_PASSWORD = os.getenv("COMPANY_DATABASE_PASSWORD")
COMPANY_DATABASE_HOST = os.getenv("COMPANY_DATABASE_HOST")
COMPANY_DATABASE_PORT = os.getenv("COMPANY_DATABASE_PORT")



""" S3 Bucket """
AWS_ACCESS_KEY = os.getenv("AWS_ACCESS_KEY")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
BUCKET_NAME = os.getenv("BUCKET_NAME")
AWS_REGION = os.getenv("AWS_REGION")
AWS_S3_URL = os.getenv("AWS_S3_URL")
S3_URL_EXPIRATION = 600
S3_BUCKET_PREFIX = "igor-company"

""" Mail server information """
EMAIL_HOST = os.getenv("EMAIL_HOST")
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
MAIL_GUN_API_KEY = os.getenv("MAIL_GUN_API_KEY")
SERVER_ENV = os.getenv("SERVER_ENV")

COMPANY = None
CURRENT_DB = None


FOLDER_EXPERIMENT = 'Experiments'
FOLDER_PROTOCOL = 'Protocols-SOPs'
FOLDER_TEMPLATE = 'Templates'
FOLDER_BUFFER = 'Buffer-Recipes'
FOLDER_STAGING_MOBILE = 'staging-mobile-uploads'
FOLDER_LANDING = 'Landing-Mobile-Uploads'
