# Generated by Django 2.1.3 on 2020-07-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
