# Generated by Django 2.1.3 on 2020-07-27 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0002_member_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='company_uid',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'sent invitation'), (2, 'accept invitation'), (3, 'deleted user')], default=0),
        ),
    ]
