# Generated by Django 2.1.3 on 2020-07-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0003_auto_20200727_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='avatar',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
