# Generated by Django 2.1.3 on 2020-07-28 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0005_memberpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabAccessMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='api_company.Member')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_member', to='api_company.Member')),
            ],
            options={
                'db_table': 'lab_access_members',
            },
        ),
    ]
