# Generated by Django 2.1.3 on 2020-07-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0006_labaccessmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('widget', models.CharField(blank=True, choices=[('text', 'text'), ('number', 'number'), ('date', 'date')], max_length=400, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'columns',
            },
        ),
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'schema',
            },
        ),
        migrations.AlterField(
            model_name='memberpermission',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_permission', to='api_company.Member'),
        ),
        migrations.AddField(
            model_name='column',
            name='schema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_company.Schema'),
        ),
    ]
