# Generated by Django 2.1.3 on 2020-07-31 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0007_auto_20200730_1038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Schema',
            new_name='Template',
        ),
        migrations.RenameField(
            model_name='column',
            old_name='schema',
            new_name='template',
        ),
        migrations.AlterModelTable(
            name='template',
            table='template',
        ),
    ]
