# Generated by Django 2.1.3 on 2020-07-31 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0009_experiment_experimentdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentdata',
            old_name='name',
            new_name='value',
        ),
    ]
