# Generated by Django 2.1.3 on 2020-07-31 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0010_auto_20200731_0831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiment',
            old_name='name',
            new_name='uid',
        ),
        migrations.AlterField(
            model_name='experimentdata',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exp_data', to='api_company.Experiment'),
        ),
    ]
