# Generated by Django 2.1.3 on 2020-08-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0013_auto_20200806_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'close')], default=0)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_company.InventoryDatabase')),
            ],
            options={
                'db_table': 'inventory_samples',
            },
        ),
        migrations.CreateModel(
            name='InventorySampleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=400, null=True)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_company.InventoryColumn')),
                ('inventory_sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sample_data', to='api_company.InventorySample')),
            ],
            options={
                'db_table': 'inventory_sample_data',
            },
        ),
    ]
