# Generated by Django 2.1.3 on 2020-08-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0015_storagetemperature'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'storage_equipment',
            },
        ),
    ]
