# Generated by Django 2.1.3 on 2020-08-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0017_storagelocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='horizontal_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='vertical_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
