# Generated by Django 2.1.3 on 2020-08-08 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0018_auto_20200807_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageequipment',
            name='is_tower',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storageequipment',
            name='tower_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
