# Generated by Django 2.1.3 on 2020-08-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0020_storagelocation_allocate_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagelocation',
            name='storage_type',
            field=models.CharField(blank=True, choices=[('box', 'box'), ('shelf', 'shelf')], max_length=400, null=True),
        ),
    ]
