# Generated by Django 2.1.3 on 2020-08-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0021_auto_20200808_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycolumn',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
