# Generated by Django 2.1.3 on 2020-08-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0022_inventorycolumn_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySampleLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=400, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_company.StorageLocation')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_company.InventorySampleData')),
            ],
            options={
                'db_table': 'inventory_sample_location',
            },
        ),
    ]
