# Generated by Django 2.1.3 on 2020-08-11 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0023_inventorysamplelocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorysamplelocation',
            old_name='sample',
            new_name='sample_data',
        ),
    ]
