# Generated by Django 2.1.3 on 2020-08-11 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0024_auto_20200811_0255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventorysamplelocation',
            name='sample_data',
        ),
        migrations.AddField(
            model_name='inventorysamplelocation',
            name='sample',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api_company.InventorySample'),
            preserve_default=False,
        ),
    ]
