# Generated by Django 2.1.3 on 2020-08-13 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0025_auto_20200811_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labaccessmember',
            name='me',
        ),
        migrations.RemoveField(
            model_name='labaccessmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberpermission',
            name='member',
        ),
        migrations.RemoveField(
            model_name='memberpermission',
            name='permission_id',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
