# Generated by Django 2.1.3 on 2020-08-13 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0026_auto_20200813_0928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, max_length=400, null=True)),
                ('role', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'sent invitation'), (2, 'accept invitation'), (3, 'deleted user')], default=0)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('company_uid', models.UUIDField(blank=True, default=None, null=True, unique=True, verbose_name='company')),
                ('avatar', models.CharField(blank=True, max_length=400, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='permission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labaccessmember',
            name='me',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='me', to='api_company.Member'),
        ),
        migrations.AddField(
            model_name='labaccessmember',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_member', to='api_company.Member'),
        ),
        migrations.AddField(
            model_name='memberpermission',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_permission', to='api_company.Member'),
        ),
    ]
