# Generated by Django 2.1.3 on 2020-08-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0028_inventorydropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorydropdown',
            name='value1',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
