# Generated by Django 2.1.3 on 2020-08-21 21:08

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0030_remove_inventorydropdown_value1'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('allDay', models.BooleanField(default=False)),
                ('color', jsonfield.fields.JSONField(default=dict)),
                ('resizable', jsonfield.fields.JSONField(default=dict)),
                ('draggable', models.BooleanField(default=False)),
                ('meta', jsonfield.fields.JSONField(default=dict)),
            ],
            options={
                'db_table': 'calendar_event',
            },
        ),
    ]
