# Generated by Django 2.1.3 on 2020-08-21 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0031_calendarevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarevent',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
