# Generated by Django 2.1.3 on 2020-08-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0033_calendarevent_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='members',
            field=models.ManyToManyField(null=True, to='api_company.Member'),
        ),
    ]
