# Generated by Django 2.1.3 on 2020-08-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0034_auto_20200828_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, to='api_company.Member'),
        ),
    ]
