# Generated by Django 2.1.3 on 2020-09-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0039_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
