# Generated by Django 2.1.3 on 2020-09-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0040_task_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCultureLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('origin', models.CharField(blank=True, max_length=400, null=True)),
                ('generic_modification', models.CharField(blank=True, max_length=400, null=True)),
                ('how_started', models.CharField(blank=True, max_length=400, null=True)),
                ('date_taken', models.DateTimeField(blank=True, null=True)),
                ('passage_number', models.IntegerField(blank=True, max_length=400, null=True)),
                ('culture_medium', models.CharField(blank=True, max_length=400, null=True)),
                ('medium_additive', models.CharField(blank=True, max_length=400, null=True)),
                ('mycoplasmas_state', models.CharField(blank=True, max_length=400, null=True)),
                ('culture_property', models.CharField(blank=True, max_length=400, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cell_culture_line',
            },
        ),
        migrations.CreateModel(
            name='CellCultureOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('field', models.CharField(blank=True, max_length=400, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cell_culture_option',
            },
        ),
    ]
