# Generated by Django 2.1.3 on 2020-09-23 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0041_cellcultureline_cellcultureoption'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCultureEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_date', models.DateTimeField(blank=True, null=True)),
                ('log_type', models.CharField(blank=True, choices=[('log_passage', 'Log Passage'), ('log_medium_change', 'Medium Change'), ('remove_cell_line', 'Remove Cell Line'), ('add_note', 'Add Note'), ('log_mycoplasma_test', 'Mycoplasma Test'), ('add_culture_medium_additive', 'Add Culture Medium Additive')], max_length=400, null=True)),
                ('remove_reason', models.CharField(blank=True, choices=[('no_longer_needed', 'No Longer Needed'), ('contaminated', 'Contaminated'), ('died', 'Died'), ('frozen_down', 'Frozen Down'), ('all_used', 'All Used'), ('other', 'Other')], max_length=400, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('mycoplasma_type', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=400, null=True)),
                ('medium_additive_text', models.TextField(blank=True, null=True)),
                ('reason_other', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell_culture_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.CellCultureLine')),
            ],
            options={
                'db_table': 'cell_culture_event',
            },
        ),
    ]
