# Generated by Django 2.1.3 on 2020-09-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0043_auto_20200923_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellcultureline',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
