# Generated by Django 2.1.3 on 2020-09-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0044_cellcultureline_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellCultureHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_cell_lines', models.CharField(blank=True, max_length=400, null=True)),
                ('log_type', models.CharField(blank=True, choices=[(0, 'Updated Date'), (1, 'Added New Cell Line'), (2, 'Added Event')], max_length=400, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.CellCultureEvent')),
                ('cell_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.CellCultureLine')),
            ],
            options={
                'db_table': 'cell_culture_history',
            },
        ),
    ]
