# Generated by Django 2.1.3 on 2020-09-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0046_cellcultureline_ended_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cellculturehistory',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
