# Generated by Django 2.1.3 on 2020-09-25 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0047_auto_20200924_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellcultureline',
            name='cloned_cell_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cellcultureline',
            name='received_scientist',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='cellculturehistory',
            name='log_type',
            field=models.CharField(blank=True, choices=[(0, 'Updated Date'), (1, 'Added New Cell Line'), (2, 'Added Event'), (3, 'Updated Cell Line')], max_length=400, null=True),
        ),
    ]
