# Generated by Django 2.1.3 on 2020-09-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0049_experimentdropdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='column',
            name='widget',
            field=models.CharField(blank=True, choices=[('text', 'text'), ('number', 'number'), ('date', 'date'), ('dropdown', 'dropdown')], max_length=400, null=True),
        ),
    ]
