# Generated by Django 2.1.3 on 2020-09-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0050_auto_20200926_1619'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CellCultureHistory',
            new_name='CellStatusHistory',
        ),
        migrations.AddField(
            model_name='cellcultureline',
            name='origin_passage_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
