# Generated by Django 2.1.3 on 2020-09-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0051_auto_20200928_1744'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cellstatushistory',
            table='cell_status_history',
        ),
    ]
