# Generated by Django 2.1.3 on 2020-09-29 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0054_auto_20200928_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellLineRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=400, null=True)),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('origin', models.CharField(blank=True, max_length=400, null=True)),
                ('generic_modification', models.CharField(blank=True, max_length=400, null=True)),
                ('how_started', models.CharField(blank=True, max_length=400, null=True)),
                ('received_scientist', models.CharField(blank=True, max_length=400, null=True)),
                ('cloned_cell_line', models.IntegerField(blank=True, null=True)),
                ('date_taken', models.DateTimeField(blank=True, null=True)),
                ('passage_number', models.IntegerField(blank=True, null=True)),
                ('culture_medium', models.CharField(blank=True, max_length=400, null=True)),
                ('medium_additive', models.CharField(blank=True, max_length=400, null=True)),
                ('mycoplasmas_state', models.CharField(blank=True, max_length=400, null=True)),
                ('culture_property', models.CharField(blank=True, max_length=400, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'cell_line_row',
            },
        ),
        migrations.RenameField(
            model_name='cellstatushistory',
            old_name='cell_line_current_status',
            new_name='cell_line_row',
        ),
        migrations.RemoveField(
            model_name='cellcultureline',
            name='origin_passage_number',
        ),
        migrations.RemoveField(
            model_name='celllinecurrentstatus',
            name='origin_passage_number',
        ),
        migrations.RemoveField(
            model_name='cellstatushistory',
            name='current_cell_lines',
        ),
        migrations.AddField(
            model_name='celllinecurrentstatus',
            name='cell_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.CellCultureLine'),
        ),
        migrations.AddField(
            model_name='cellstatushistory',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
