# Generated by Django 2.1.3 on 2020-09-29 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0056_auto_20200929_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellcultureline',
            name='mycoplasmas_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celllinecurrentstatus',
            name='mycoplasmas_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='celllinerow',
            name='mycoplasmas_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
