# Generated by Django 2.1.3 on 2020-09-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0057_auto_20200929_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellstatushistory',
            name='latest',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cellcultureevent',
            name='mycoplasma_type',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Negative', 'Negative')], max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='celllinecurrentstatus',
            name='cell_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_status', to='api_company.CellCultureLine'),
        ),
    ]
