# Generated by Django 2.1.3 on 2020-09-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0058_auto_20200929_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellstatushistory',
            name='ui_event_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cellstatushistory',
            name='log_type',
            field=models.CharField(blank=True, choices=[(0, 'Updated Date'), (1, 'Added New Cell Line'), (2, 'Added Event'), (3, 'Updated Cell Line'), (4, 'Remove history')], max_length=400, null=True),
        ),
    ]
