# Generated by Django 2.1.3 on 2020-09-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0059_auto_20200930_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellcultureevent',
            name='removed',
            field=models.BooleanField(default=False),
        ),
    ]
