# Generated by Django 2.1.3 on 2020-10-01 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0060_cellcultureevent_removed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('PLATE', 'Plate'), ('FILE', 'File'), ('IMAGE', 'Image'), ('TABLE', 'Table'), ('TEXT', 'Text')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.Experiment')),
            ],
            options={
                'db_table': 'experiment_entry',
            },
        ),
        migrations.CreateModel(
            name='ExperimentEntryVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(blank=True)),
                ('url', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('PLATE', 'Plate'), ('FILE', 'File'), ('IMAGE', 'Image'), ('TABLE', 'Table'), ('TEXT', 'Text')], max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'experiment_entry_version',
            },
        ),
        migrations.CreateModel(
            name='ExperimentVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('experiment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.Experiment')),
            ],
            options={
                'db_table': 'experiment_version',
            },
        ),
        migrations.AddField(
            model_name='experimententryversion',
            name='experiment_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_company.ExperimentVersion'),
        ),
    ]
