# Generated by Django 2.1.3 on 2020-10-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0061_auto_20201001_0407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimententry',
            name='url',
        ),
        migrations.RemoveField(
            model_name='experimententryversion',
            name='url',
        ),
    ]
