# Generated by Django 2.1.3 on 2020-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0064_experiment_assigned_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('members', models.ManyToManyField(to='api_company.Member')),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
