# Generated by Django 2.1.3 on 2020-10-06 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0066_auto_20201006_0421'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=400, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('in_planing', 'In Planing'), ('on_hold', 'On Hold')], max_length=400, null=True)),
                ('members', models.ManyToManyField(to='api_company.Member')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api_company.Project')),
            ],
            options={
                'db_table': 'project_task',
            },
        ),
    ]
