# Generated by Django 2.1.3 on 2020-10-12 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0069_auto_20201008_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='projecttaskcomment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api_company.ProjectTask'),
        ),
    ]
