# Generated by Django 2.1.3 on 2020-10-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0072_projecthistory_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttask',
            name='status',
            field=models.CharField(blank=True, choices=[('done', 'Done'), ('in_progress', 'In Progress'), ('in_planing', 'In Planing'), ('on_hold', 'On Hold'), ('deleted', 'Deleted')], max_length=400, null=True),
        ),
    ]
