# Generated by Django 2.1.3 on 2020-10-13 05:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0074_auto_20201012_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskevent',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
