# Generated by Django 2.1.3 on 2020-10-13 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0075_projecttaskevent_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projecttaskevent',
            name='project_history',
        ),
        migrations.RemoveField(
            model_name='projecttaskevent',
            name='task',
        ),
        migrations.RemoveField(
            model_name='projecttaskevent',
            name='task_history',
        ),
        migrations.AddField(
            model_name='projecttaskevent',
            name='after_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_project', to='api_company.ProjectHistory'),
        ),
        migrations.AddField(
            model_name='projecttaskevent',
            name='after_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='after_task', to='api_company.ProjectTaskHistory'),
        ),
        migrations.AddField(
            model_name='projecttaskevent',
            name='before_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before_project', to='api_company.ProjectHistory'),
        ),
        migrations.AddField(
            model_name='projecttaskevent',
            name='before_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='before_task', to='api_company.ProjectTaskHistory'),
        ),
    ]
