# Generated by Django 2.1.3 on 2020-10-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0076_auto_20201013_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskevent',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='api_company.ProjectTask'),
        ),
    ]
