# Generated by Django 2.1.3 on 2020-10-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_company', '0079_auto_20201016_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttaskevent',
            name='first_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='projecttaskevent',
            name='last_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
