# Generated by Django 2.1.3 on 2020-07-24 10:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('first_name', models.CharField(blank=True, max_length=400, null=True)),
                ('last_name', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('db_name', models.CharField(blank=True, max_length=400, null=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'sent invitation'), (2, 'accept invitation')], default=0)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
