# Generated by Django 2.1.3 on 2020-07-28 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0006_permission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
