# Generated by Django 2.1.3 on 2020-08-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0007_delete_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='company',
        ),
    ]
