# Generated by Django 2.1.3 on 2020-08-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_base', '0009_auto_20200813_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.IntegerField(choices=[(0, 'pending'), (1, 'sent invitation'), (2, 'accept invitation'), (3, 'deleted account')], default=0),
        ),
    ]
